### ISSUE TITLE
using three-mesh-bvh for raycasting

### ISSUE THREAD

**Issue by arpu** [andstor/voxelizer#21]
Hey,

would it make sense to use https://github.com/gkjohnson/three-mesh-bvh ? for speed up raycasting

**Comment by andstor** [comment]
Hi 👋 

I am actually using it in the RaycastAlgorithm! https://github.com/andstor/voxelizer/blob/51f5c7c6812efff5adc5cfe67ff5d577d398b727/src/algorithms/RaycastAlgorithm.js#L7 

I have done some quite extensive research of various raycasting optimization solutions for threejs, and the [three-mesh-bvh](https://github.com/gkjohnson/three-mesh-bvh) seems to be by far the best alternative.

However, [three-mesh-bvh](https://github.com/gkjohnson/three-mesh-bvh) requires modifications on the prototype of the threejs [Mesh](https://threejs.org/docs/#api/en/objects/Mesh) class. Depending on how the user loads up the voxelizer engine in relation to threejs, Mesh objects might be instantiated before the methods on the Mesh prototype are modified. One option is to modify the prototype after the object is instantiated. This could be done with the [`Object.setPrototypeOf()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf). However, this is considered bad practice and results in bad performance (although I have not actually tested this).

I have been wanting implement a more safe and reliable way of ensuring the raycasting optimizations does take effect. At the very least, it should be document how to ensure the optimizations does take effect.

Is this something you would be interested in taking a look at @arpu ?

**Comment by arpu** [comment]
Hey
wau i missed that you use three-mesh-bvh now! awesome stuff

i only found this, on testing different voxelizer and your, is just the best!  only problem i see is on resolution >= 400 
my browser tab crashes

nothing i can help on this :/

**Comment by arpu** [comment]
i think this can be simple be closed!
