### ISSUE TITLE
[Feature Request] export as gltf/glb model with threjjs GLTFExporter and vox bin model 

### ISSUE THREAD

**Issue by arpu** [andstor/voxelizer#23]
hello

would be cool to export to glb/gltf model and vox bin format

**Comment by arpu** [comment]
hmm looks like voxbin should work to import but i get 
Uncaught Error: Id of .vox-file should be "VOX ", found "#bin".

**Comment by arpu** [comment]
if i use your https://github.com/andstor/three-voxel-loader  to try view and export to glb

**Comment by andstor** [comment]
Hi,
i guess you mean `binvox` and not `voxbin`? It seems that you might be confused by the VOX file format importing support available in three-voxel-loader.

If you export a binvox file from Voxelizer, then you should be able to import it with the **binvox importer** in three-voxel-loader. Then, you could export the loaded model with the threejs GLTFExporter.

**Comment by arpu** [comment]
ok thx a lot for the clarification will try with the  binvox importer in three-voxel-loader.

**Comment by arpu** [comment]
i think this can be close

**Comment by arpu** [comment]
ok but i get 
voxel-loader.js:26 Uncaught Error: Unsupported type (binvox).

the binvox file is


[voxels.zip](https://github.com/andstor/voxelizer/files/4997416/voxels.zip)

**Comment by arpu** [comment]
ok found the problem 
the example use a old voxel-loader
https://github.com/andstor/three-voxel-loader/blob/master/examples/index.html#L13


will close this here and add it to the  voxel-loader git
